DM: Externalize terminal logic

diff --git a/update_wrapper b/update_wrapper
--- a/update_wrapper
+++ b/update_wrapper
@@ -40,11 +40,21 @@ __is_user_allowed_to_update(){
 	fi
 }
 
-default_dir=${HOME}/.local/update_script/scripts
+__call_xterm(){
+    local update_with="$1"
+    if [ "${f_port}" == "true" ]; then
+        /bin/sh ${default_dir}/update_with_xterm -p ${update_with}
+    elif [ "${f_world}" == "true" ]; then
+		/bin/sh ${default_dir}/update_with_xterm -w
+    fi
+}
+
+__call_bash(){
+    echo "TODO"
+}
+
+default_dir=${HOME}/.local/update_script/scripts/update_scripts
 config_file=${default_dir}/update.config
-config_world_file=${default_dir}/update_world.config
-update_ports_log=${default_dir}/update_ports.log
-update_world_log=${default_dir}/update_world.log
 batch_update=''
 f_port="true"
 f_world="false"
@@ -70,6 +80,7 @@ done
 batch_update_flag=$(__read_property batch)
 update_with=$(__read_property update_with)
 updater_group=$(__read_property updater_group)
+with_terminal=$(__read_property with_terminal)
 is_user_allowed_to_update=$(__is_user_allowed_to_update ${updater_group})
 xterm=$(command -v xterm)
 
@@ -87,20 +98,15 @@ if [ "${batch_update_flag}" == "true" ]; then
 	batch_update='-b'
 fi
 
-if [ "${f_port}" == "true" ]; then
-	if [ "${update_with}" == "pkg" ]; then
-		#xterm -title "Update Ports with PKG" -e su root -c "${HOME}/.local/scripts/update_pkg"
-		${xterm} -title "Update Ports with PKG" -hold -e "${HOME}/.local/scripts/update_pkg"
-	elif [ "${update_with}" == "port" ]; then
-		${xterm} -title "Update Ports with PORTUPGRADE" -hold -e su root -c "${HOME}/.local/scripts/update_ports ${batch_update}"
-	else
-		echo "[ERROR] Option not recognised"
-		exit 1
-	fi
-fi
 
-if [ "${f_world}" == "true" ]; then
-	${xterm} -title "Update World" -hold -e su root -c "${HOME}/.local/scripts/update_world -c ${config_world_file}"
+if [ "${with_terminal}" == "xterm" ]; then
+    __call_xterm ${update_with}
+elif [ "${with_terminal}" == "bash" ]; then
+    __call_bash
+    exit 1
+else
+    echo "[ERROR] Option not recognised"
+    exit 1
 fi
 
 exit 0
